import type { NextPage } from 'next'
import Header from '../../components/Header/Header'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Teste from '../../components/Teste/teste'

const teste: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div className={styles.container}>
                <main className={styles.main}>
                    <div>
                        <Teste value='Nome' name='Message' />
                    </div>
                </main>
            </div>
        </>
    )
}

export default teste