import { FC } from 'react'
import Head from 'next/head'
const Title: FC = () => {
    return(
        <>
            <Head>
            <title>Programação intença</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
        </>
    )
}
export default Title;